export const SHOWGALLERY='SHOWGALLERY';
export const INVITECAKE='INVITECAKE';
export const ADDTOCART='ADDTOCART';
export const REMOVEFROMCART='REMOVEFROMCART';
export const REDUCEFROMCART='REDUCEFROMCART';

export const SHOWCART='SHOWCART';